# Generated by Django 5.1.7 on 2025-03-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnglishToOjibweLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_text', models.TextField()),
                ('ojibwe_text', models.TextField()),
                ('definition', models.TextField(blank=True, null=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
            ],
            options={
                'db_table': 'english_to_ojibwe_local',
            },
        ),
        migrations.CreateModel(
            name='EnglishWord',
            fields=[
                ('word', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'english_dict',
            },
        ),
        migrations.CreateModel(
            name='OjibweToEnglishLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ojibwe_text', models.TextField()),
                ('english_text', models.JSONField()),
                ('version', models.CharField(default='1.0', max_length=20)),
            ],
            options={
                'db_table': 'ojibwe_to_english_local',
            },
        ),
    ]
