# Generated by Django 5.1.7 on 2025-03-26 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingTranslationLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_text', models.TextField()),
                ('frequency', models.FloatField(default=0.0)),
                ('version', models.CharField(default='1.0', max_length=20)),
            ],
            options={
                'db_table': 'missing_translations_local',
            },
        ),
        migrations.CreateModel(
            name='SemanticMatchLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_text', models.TextField()),
                ('ojibwe_text', models.TextField()),
                ('similarity', models.FloatField()),
                ('english_definition', models.TextField(blank=True, null=True)),
                ('ojibwe_definition', models.TextField(blank=True, null=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
            ],
            options={
                'db_table': 'semantic_matches_local',
            },
        ),
    ]
